//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gig
    {
        public string ArtistId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Venue { get; set; }
        public byte GenreId { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
